[build]
  command = "pip install -r requirements.txt && python api.py"
  publish = "public"

[[redirects]]
  from = "/predict"
  to = "/predict"
  status = 200
  force = true

[[redirects]]
  from = "/predict/graph"
  to = "/predict/graph"
  status = 200
  force = true